version: "2.3"

services:
  nginx:
    container_name: greenapi-nginx
    build: ./nginx
    ports:
      - "81:80"
    volumes:
      - ./www:/var/www/greenapi
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`green.fap.pw`)"
      - "traefik.http.routers.nginx.entrypoints=https"
      - "traefik.http.services.nginx.loadbalancer.server.port=81"
    depends_on:
      php:
        condition: service_healthy
    restart: always

  php:
    container_name: greenapi-php
    build: ./php
    volumes:
      - ./www:/var/www/greenapi
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 1s
    restart: always

networks:
  default:
    name: proxy-network
    external: true