version "2.3"

services:
  nginx:
    container_name: greenapi-nginx
    build: ./Dockerfile_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/greenapi
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      php:
        condition: service_healthy
    restart: always

  php:
    container_name: greenapi-php
    build: ./Dockerfile_php
    volumes:
      - ./www:/var/www/greenapi
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 1s
    restart: always

  certbot:
    image: certbot/cerbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw